### ISSUE TITLE
Internal `reporter` is not reporting properly

### ISSUE THREAD

**Issue by xavierfoucrier** [center-key/w3c-html-validator#13]
Hello @dpilafian 👋 

I am having another issue with the internal `reporter`.
May be I am missing something, let me know 😉 

![image](https://github.com/center-key/w3c-html-validator/assets/2471223/5c2f663c-a3cb-4059-acd4-e569b3ded4c3)

Here is (part of) my code:
```js
glob.sync('./dist/**/*.html').map(page => {
  w3cHtmlValidator.validate({
    filename: page,
  }).then(w3cHtmlValidator.reporter)
});
```

> Note that with a regular `then(console.log)` I am not having any issue and package properly report to the console.

**Comment by pilafmon** [comment]
The `reporter()` fuction is throwing an exception because your **index.html** file has a validation error.  You can configure this behavior with the `continueOnFail` option.

Change:
```javascript
.then(w3cHtmlValidator.reporter)
```
to:
```javascript
.then(results => w3cHtmlValidator.reporter(results, { continueOnFail: true }))
```

Note that throwing the exception is done deliberately in order to support aborting a CI process when a test fails.

**Comment by xavierfoucrier** [comment]
Hello @dpilafian 👋 

Yes I remember asking for this a while ago 😄 
https://github.com/center-key/w3c-html-validator/issues/6

The problem here is that I am still running the validator inside a Github Action... so I would like to report and not continue on failure. I guess it's not implemented yet? 🤔 

With the updated code and `continueOnFail: true`, the action will succeed:

![image](https://github.com/center-key/w3c-html-validator/assets/2471223/b30116f9-442a-41e9-bd01-b8cc95b8e0a6)

If running with `continueOnFail: false`, the action fail as expected, since I have added an issue inside the HTML code:

![image](https://github.com/center-key/w3c-html-validator/assets/2471223/bc1d8e7f-084f-446c-be3f-a97e298e8a35)

Not sure it's not the expected failure/exit from the validator... let me know!
Thanks 😉

**Comment by xavierfoucrier** [comment]
Currently, if I set `continueOnFail: false`, I will get this error:

![image](https://github.com/center-key/w3c-html-validator/assets/2471223/c59fe608-9721-49da-9341-1b191a40683b)

**Comment by xavierfoucrier** [comment]
Hello @dpilafian 👋 

Did you read my answer to this?
I am just wondering if it's the expected failure/exit from the validator?

Thanks a lot! 😉

**Comment by pilafmon** [comment]
I'm not clear what the question is since the errors are reported in both cases.  Both of the screenshots show the error messages.  Are you expecting the errors to be hidden?

**Comment by xavierfoucrier** [comment]
Hello @dpilafian 👋 

Understood, in fact I was expecting the stack trace to be hidden, of course the HTML errors we need to display them, but the stack trace I am not sure, but may you can find a case where it's necessary to have.

Let me know, and then we can close it 😉

**Comment by pilafmon** [comment]
The stack trace is not actually being printed out by **w3c-html-validator** itself.  The stack trace is printed by whoever is catching the exception, which will usually be your **package.json** `"scripts"` task.

You can use the `--stack-trace-limit` flag to tell **node** to suppress the stack trace, but it's a rather ugly hack and decreases maintainability.  In this case, the medicine is probably worse than the disease.

Regular way to validate the **website** folder:
```json
   "scripts": {
      "test": "html-validator website"
   },
```

Validate but suppress the stack trace:
```json
   "scripts": {
      "test": "node --stack-trace-limit=0 node_modules/w3c-html-validator/bin/cli.js website"
   },
```

Note that while the stack trace is suppressed (`0` lines printed), the JS error itself is still printed.

**Comment by pilafmon** [comment]
Just a heads up that you need to throttle your `glob.sync('./dist/**/*.html').map()` processing or risk getting rejected by the W3C server.

https://github.com/center-key/w3c-html-validator/blob/a5da3ad3574d4d6f01d9a2d39288d2ba08e6d374/bin/cli.js#L77-L78

**Comment by xavierfoucrier** [comment]
Hello @dpilafian 👋 

Thanks for all the feedbacks!
It's really appreciated.

I will care of updating the `w3c-html-validator` package on my side and keep error reporting as is 😉 
Again, thanks for the fix!

> I don't really have a lot of pages to checks with the W3C validator, most time in my base setup I will have two pages, and most time in other projects I can have 10-15 pages maximum to check, currently never get rejected by W3C, but good to know ✔️
