### ISSUE TITLE
unsupported syntax on older versions of nodejs

### ISSUE THREAD

**Issue by kevintap-idemia** [center-key/w3c-html-validator#3]
The tsconfig.json for this project compiles to a target of ES2020. However, there is no engines declaration in package.json indicating that nodejs v14 or greater with ?. operator support is a requirement to run this package.

Trying to run this package on older versions of nodejs produces an error:

node_modules/w3c-html-validator/dist/w3c-html-validator.js:37
            html: 'HTML String (characters: ' + inputHtml?.length + ')',

Indicating that the ?. operator is not supported.

The tsconfig.json should be updated to compile to a lower target version or the package.json should be updated to specify that this package requires a minimum nodejs version to run.

**Comment by pilafmon** [comment]
Good catch.

I just did a quick test using:
```json
      "target": "ES2015",
```
and it seems to work fine.

Both the fixes you suggested look reasonable to me.  If you want to submit a pull request with your preferred fix, I'll get it merged and released immediately.
