### ISSUE TITLE
Please help me to solve the plugin crash during file validation

### ISSUE THREAD

**Issue by Alecto** [center-key/w3c-html-validator#7]
the problem appeared after updating the plugin from 1.1.0 to version 1.3.0

index.html
![image](https://user-images.githubusercontent.com/8464662/214530158-f2a2b2b3-40d5-439b-a6e3-1e143b225fdb.png)

now online validation:
![image](https://user-images.githubusercontent.com/8464662/214528926-6bae965f-1c8d-426f-8107-4da570daf5fa.png)

now validation with the plugin:
![image](https://user-images.githubusercontent.com/8464662/214528950-75f11a82-3a04-48eb-bad0-68a596fe8d52.png)

in package.json
![image](https://user-images.githubusercontent.com/8464662/214529285-4c199efa-b7f7-4a98-85ee-211d6b3cd4b9.png)

in package-lock.json
![image](https://user-images.githubusercontent.com/8464662/214529770-8373fdcb-798f-4c0e-b93d-a55903b5d5b9.png)

files for validation are inserted by the script
![image](https://user-images.githubusercontent.com/8464662/214529521-6a63a2f8-f17d-4616-a009-8af1bec28391.png)

Please help me figure out what the problem is?
Perhaps it is required to replace some options when calling the plugin? or a script?

Or is it enough to handle errors in the .catch block?

Thanks in advance for your help.

**Comment by pilafmon** [comment]
By default the `w3cHtmlValidator.reporter()` function now throws an error when a validation fails (this allows CI build and test scripts to properly abort when invalid HTML is encountered).

Use the `continueOnFail` option to specify you do not want an error thrown.

On line 33 of **actions/validator.js** replace:
```javascript
w3cHtmlValidator.reporter(res);
```
with:
```javascript
w3cHtmlValidator.reporter(res, { continueOnFail: true });
```

For anyone using the CLI, add the `--continue` flag, like:
```shell
$ w3c-html-validator website/index.html --continue
```

**Comment by Alecto** [comment]
thanks a lot, it worked!
