### ISSUE TITLE
Trailing slash on void elements

### ISSUE THREAD

**Issue by GorskiAnthony** [center-key/w3c-html-validator#8]
Hello, I'm trying not to display this info

```shell
[11:08:21] HTML info: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.
[11:08:21] line 4, column 3: <head> <meta charset="UTF-8" />\n <me
```

Is it possible to pass a parameter that does?

**Comment by pilafmon** [comment]
That trailing slash is quite ugly.  If you absolutely must allow that hideous remnant of XHTML, there's now an `--ignore` flag in **v1.3.2** to specify validation messages to skip.

Example:
```json
"script": {
   "test": "html-validator docs/*.html '--ignore=Trailing slash on void elements'"
},
```

**Comment by GorskiAnthony** [comment]
Thx 💪 
Yes, I know, I will configure VS Code to compensate for this 😅
